name = "stashflow-edge"
main = "build/worker/shim.mjs"
compatibility_date = "2026-06-24"

[build]
command = "worker-build --release"

[[kv_namespaces]]
binding = "STASHFLOW_KV"
id = "670d2b7fe2e34b388e0283c615b878cd"
